# dataset config
field_separator: "\t" #指定数据集field的分隔符
seq_separator: " " #指定数据集中token_seq或者float_seq域里的分隔符
data_path: "dataset"
dataset_save_path: ""
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: tracks_id #指定物品id域
RATING_FIELD: num_repeat #指定打分rating域
TIME_FIELD: timestamp #指定时间域
NEG_PREFIX: neg_ #指定负采样前缀
LABEL_FIELD: label #指定标签域
#因为数据集没有标签，所以设置一个阈值，认为rating高于该值的是正例，反之是负例
threshold:
    num_repeat: 2
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列,剩下的以此类推
load_col:
    inter: [user_id, tracks_id, num_repeat]
    user: [user_id]
    item: [tracks_id]

user_inter_num_interval: [20,1000000]
item_inter_num_interval: [400,1000000] 

# training settings
epochs: 500 #训练的最大轮数

learner: adam #使用的pytorch内置优化器
learning_rate: 0.005 #学习率

eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

use_cb: true
use_audio: true
afeat_layer: 11
a_feature_path: "dataset/m4a/m4a-muq.pkl"
wav_mlp_sizes: [64]